Cherry pick of bd114fddb78df092c27a64db9825e7b395088a58 failed
stdout:
Auto-merging l10n_ar_afipws_fe/models/account_move.py
CONFLICT (content): Merge conflict in l10n_ar_afipws_fe/models/account_move.py

stderr:
20:09:22.272723 git.c:444               trace: built-in: git cherry-pick bd114fddb78df092c27a64db9825e7b395088a58
error: could not apply bd114fd... [FIX] Fix issue https://github.com/ingadhoc/odoo-argentina-ce/issues/28 and  https://github.com/ingadhoc/odoo-argentina-ce/issues/32
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status: